import { Inter } from "next/font/google";
import Navbar from "./components/navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Earthie - Admin",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='w-screen flex'>
                    <Navbar />
                    
                    {children}
                </div>
            </body>
        </html>
    );
}
